# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelBackupPath = QtWidgets.QLabel(self.centralwidget)
        self.labelBackupPath.setObjectName("labelBackupPath")
        self.horizontalLayout_2.addWidget(self.labelBackupPath)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tbtnChangeBackup = QtWidgets.QToolButton(self.centralwidget)
        self.tbtnChangeBackup.setObjectName("tbtnChangeBackup")
        self.horizontalLayout_2.addWidget(self.tbtnChangeBackup)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddDir = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddDir.setObjectName("btnAddDir")
        self.horizontalLayout.addWidget(self.btnAddDir)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnDeleteDir = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteDir.setObjectName("btnDeleteDir")
        self.horizontalLayout.addWidget(self.btnDeleteDir)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnActivate = QtWidgets.QPushButton(self.centralwidget)
        self.btnActivate.setObjectName("btnActivate")
        self.verticalLayout.addWidget(self.btnActivate)
        self.btnActivateAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnActivateAll.setObjectName("btnActivateAll")
        self.verticalLayout.addWidget(self.btnActivateAll)
        self.btnDeactivate = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeactivate.setObjectName("btnDeactivate")
        self.verticalLayout.addWidget(self.btnDeactivate)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 3, 3, 1, 1)
        self.btnBackup = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackup.setObjectName("btnBackup")
        self.gridLayout.addWidget(self.btnBackup, 4, 3, 1, 1)
        self.listDir = QtWidgets.QListWidget(self.centralwidget)
        self.listDir.setObjectName("listDir")
        self.gridLayout.addWidget(self.listDir, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelBackupPath.setText(_translate("MainWindow", "Backup Path"))
        self.tbtnChangeBackup.setText(_translate("MainWindow", "..."))
        self.btnAddDir.setText(_translate("MainWindow", "Add Directory"))
        self.btnDeleteDir.setText(_translate("MainWindow", "Delete Directory"))
        self.btnActivate.setText(_translate("MainWindow", "Activate"))
        self.btnActivateAll.setText(_translate("MainWindow", "Activate All"))
        self.btnDeactivate.setText(_translate("MainWindow", "Deactivate"))
        self.btnBackup.setText(_translate("MainWindow", "Backup"))
